insert into admin(name, password, accesLevel) values("B-Dionysus", "god", 100);
insert into status(status) values("Portfolio");
insert into status(status) values("Private");
insert into status(status) values("Archived");
insert into projectCat(title, about, tabName, thumbnail, addedBy, displayOrder, status) 
values("Benjamin Dionysus", "Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes laborious physical exercise, except to obtain some advantage from it? But who has any right to find fault with a man who chooses to enjoy a pleasure that has no annoying consequences, or one who avoids a pain that produces no resultant pleasure?", "Main Page", "./assets/img/mainPhoto.2b.png", 1, 1, 1);
insert into projectCat(title, about, tabName, thumbnail, addedBy, displayOrder, status) 
values("Web Development", "Full stack web development projects. HTML, CSS, JS, mySQL, and so on.", "Web Dev", "https://via.placeholder.com/150", 1, 2, 1);
insert into projectCat(title, about, tabName, thumbnail, addedBy, displayOrder, status) 
values("Microcontroller Projects", "Teensy and Arduino controllers. C++", "Arduino", "https://via.placeholder.com/150", 1, 3, 1);
insert into projectCat(title, about, tabName, thumbnail, addedBy, displayOrder, status) 
values("Music performance and composition", "Performance and composition. Piano, modular synthesis, Ableton Live, &c.", "Music", "https://via.placeholder.com/150", 1, 4, 1);
insert into projects(title, about, displayName, externalLink, thumbnail, imageGallery, displayOrder, status, projectId)
values("Database-driven Portfolio Page", "But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful.", "Portfolio Page", "https://github.com/B-Dionysus/", "https://via.placeholder.com/150", "", 1, 1, 2);

insert into projects(title, about, displayName, externalLink, thumbnail, imageGallery, displayOrder, status, projectId)
values("Database-driven Portfolio Page", "But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful.", "Portfolio Page", "https://github.com/B-Dionysus/", "https://via.placeholder.com/150", "", 2, 1, 2);
insert into projects(title, about, displayName, externalLink, thumbnail, imageGallery, displayOrder, status, projectId)
values("Database-driven Portfolio Page", "But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful.", "Portfolio Page", "https://github.com/B-Dionysus/", "https://via.placeholder.com/150", "", 3, 1, 2);
insert into projects(title, about, displayName, externalLink, thumbnail, imageGallery, displayOrder, status, projectId)
values("Database-driven Portfolio Page", "But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful.", "Portfolio Page", "https://github.com/B-Dionysus/", "https://via.placeholder.com/150", "", 1, 1, 3);
insert into projects(title, about, displayName, externalLink, thumbnail, imageGallery, displayOrder, status, projectId)
values("Database-driven Portfolio Page", "But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful.", "Portfolio Page", "https://github.com/B-Dionysus/", "https://via.placeholder.com/150", "", 2, 1, 3);
insert into projects(title, about, displayName, externalLink, thumbnail, imageGallery, displayOrder, status, projectId)
values("Database-driven Portfolio Page", "But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful.", "Portfolio Page", "https://github.com/B-Dionysus/", "https://via.placeholder.com/150", "", 3, 1, 3);
insert into projects(title, about, displayName, externalLink, thumbnail, imageGallery, displayOrder, status, projectId)
values("Database-driven Portfolio Page", "But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful.", "Portfolio Page", "https://github.com/B-Dionysus/", "https://via.placeholder.com/150", "", 1, 1, 4);
insert into projects(title, about, displayName, externalLink, thumbnail, imageGallery, displayOrder, status, projectId)
values("Database-driven Portfolio Page", "But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful.", "Portfolio Page", "https://github.com/B-Dionysus/", "https://via.placeholder.com/150", "", 2, 1, 4);
